// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/inventory": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取库存列表，支持按产品变体和店铺筛选，并支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "库存管理"
                ],
                "summary": "获取库存列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品变体ID",
                        "name": "product_variant_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "店铺ID",
                        "name": "store_id",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量，默认10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取库存列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Inventory"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的库存记录，需提供产品变体ID、店铺ID和库存数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "库存管理"
                ],
                "summary": "创建库存",
                "parameters": [
                    {
                        "description": "库存信息",
                        "name": "inventory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Inventory"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Inventory"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "产品变体或店铺不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "库存记录已存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inventory/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID获取库存的详细信息，包括产品变体和店铺信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "库存管理"
                ],
                "summary": "获取库存详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "库存ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取库存详情",
                        "schema": {
                            "$ref": "#/definitions/models.Inventory"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "库存不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新现有库存记录，可以修改库存数量并提供更新原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "库存管理"
                ],
                "summary": "更新库存",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "库存ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "库存信息",
                        "name": "inventory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Inventory"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "库存不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定ID的库存记录，此操作不可逆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "库存管理"
                ],
                "summary": "删除库存",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "库存ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "库存不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取会员列表，支持按名称、手机号和等级筛选，并支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会员管理"
                ],
                "summary": "获取会员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会员名称（模糊查询）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "手机号码（模糊查询）",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "regular",
                            "silver",
                            "gold",
                            "platinum",
                            "diamond"
                        ],
                        "type": "string",
                        "description": "会员等级",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量，默认10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取会员列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Member"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的会员，需提供必要的会员信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会员管理"
                ],
                "summary": "创建会员",
                "parameters": [
                    {
                        "description": "会员信息",
                        "name": "member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Member"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误或手机号已被注册",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/members/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID获取会员的详细信息，包括基本信息、等级、积分等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会员管理"
                ],
                "summary": "获取会员详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "会员ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取会员详情",
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会员不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新现有会员的信息，需提供完整的会员信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会员管理"
                ],
                "summary": "更新会员",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "会员ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "会员信息",
                        "name": "member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会员不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定ID的会员，此操作不可逆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会员管理"
                ],
                "summary": "删除会员",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "会员ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会员不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取商品列表，支持按名称、SKU、分类等条件筛选，并支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品管理"
                ],
                "summary": "获取商品列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商品名称（模糊查询）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品SKU（模糊查询）",
                        "name": "sku",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品分类ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量，默认10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取商品列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Product"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的商品及其变体，需提供商品基本信息和变体信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品管理"
                ],
                "summary": "创建商品",
                "parameters": [
                    {
                        "description": "商品信息",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "商品SKU已存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID获取商品的详细信息，包括基本信息、变体、价格等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品管理"
                ],
                "summary": "获取商品详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取商品详情",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "商品不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新现有商品及其变体，需提供完整的商品信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品管理"
                ],
                "summary": "更新商品",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "商品信息",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "商品不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "商品SKU已被其他商品使用",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/suppliers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取供应商列表，支持按名称、编码、类型和状态筛选，并支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "供应商管理"
                ],
                "summary": "获取供应商列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "供应商名称（模糊查询）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "供应商编码（模糊查询）",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "manufacturer",
                            "distributor",
                            "retailer",
                            "wholesaler",
                            "other"
                        ],
                        "type": "string",
                        "description": "供应商类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "active",
                            "inactive"
                        ],
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量，默认10",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取供应商列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Supplier"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的供应商，需提供必要的供应商信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "供应商管理"
                ],
                "summary": "创建供应商",
                "parameters": [
                    {
                        "description": "供应商信息",
                        "name": "supplier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateSupplierRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/models.Supplier"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或供应商编码已存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/suppliers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID获取供应商的详细信息，包括基本信息、联系方式、评级等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "供应商管理"
                ],
                "summary": "获取供应商详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "供应商ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取供应商详情",
                        "schema": {
                            "$ref": "#/definitions/models.Supplier"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "供应商不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新现有供应商的信息，需提供完整的供应商信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "供应商管理"
                ],
                "summary": "更新供应商",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "供应商ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "供应商信息",
                        "name": "supplier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateSupplierRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/models.Supplier"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或供应商编码已被其他供应商使用",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "供应商不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定ID的供应商，如果供应商已被采购单引用则无法删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "供应商管理"
                ],
                "summary": "删除供应商",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "供应商ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "供应商已被采购单引用，无法删除",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "供应商不存在",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.CreateSupplierRequest": {
            "type": "object",
            "required": [
                "code",
                "name",
                "type"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "contact_person": {
                    "type": "string"
                },
                "contact_phone": {
                    "type": "string"
                },
                "delivery_terms": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "payment_terms": {
                    "type": "string"
                },
                "qualification": {
                    "type": "string"
                },
                "rating": {
                    "$ref": "#/definitions/models.SupplierRating"
                },
                "status": {
                    "type": "boolean"
                },
                "type": {
                    "$ref": "#/definitions/models.SupplierType"
                }
            }
        },
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据"
                },
                "error": {
                    "description": "错误信息，仅在发生错误时返回",
                    "type": "string",
                    "example": "错误信息"
                },
                "message": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "models.ConsumptionLevel": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high",
                "luxury"
            ],
            "x-enum-comments": {
                "High": "高",
                "Low": "低",
                "Luxury": "奢侈",
                "Medium": "中"
            },
            "x-enum-varnames": [
                "Low",
                "Medium",
                "High",
                "Luxury"
            ]
        },
        "models.Dictionary": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "字典类型编码",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "description": "关联",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DictionaryItem"
                    }
                },
                "name": {
                    "description": "字典类型名称",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态：启用/禁用",
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.DictionaryItem": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "字典项编码",
                    "type": "string"
                },
                "color": {
                    "description": "颜色值（用于前端展示）",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "dictionary": {
                    "description": "关联",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Dictionary"
                        }
                    ]
                },
                "dictionaryCode": {
                    "description": "关联的字典类型编码",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "字典项名称",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态：启用/禁用",
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "description": "字典项值",
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "description": "详细错误信息，仅在开发环境返回",
                    "type": "string"
                },
                "message": {
                    "description": "错误消息",
                    "type": "string",
                    "example": "参数错误"
                }
            }
        },
        "models.Inventory": {
            "type": "object",
            "properties": {
                "alertQuantity": {
                    "description": "预警数量",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastCheckTime": {
                    "description": "最后盘点时间",
                    "type": "string"
                },
                "productVariant": {
                    "description": "商品变体",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ProductVariant"
                        }
                    ]
                },
                "productVariantID": {
                    "description": "商品变体ID",
                    "type": "integer"
                },
                "quantity": {
                    "description": "库存数量",
                    "type": "integer"
                },
                "store": {
                    "description": "关联",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Store"
                        }
                    ]
                },
                "storeID": {
                    "description": "店铺ID",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Member": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "bodyHeight": {
                    "description": "体型数据",
                    "type": "integer"
                },
                "bodyWeight": {
                    "description": "体重(kg)",
                    "type": "integer"
                },
                "bustSize": {
                    "description": "胸围(cm)",
                    "type": "integer"
                },
                "consumptionLevel": {
                    "description": "消费能力",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ConsumptionLevel"
                        }
                    ]
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "favoriteCategories": {
                    "description": "喜欢的品类，逗号分隔",
                    "type": "string"
                },
                "favoriteColors": {
                    "description": "喜欢的颜色，逗号分隔",
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "hipSize": {
                    "description": "臀围(cm)",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "inseam": {
                    "description": "内缝长度(cm)",
                    "type": "integer"
                },
                "lastPurchaseDate": {
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/models.MemberLevel"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "description": "备注",
                    "type": "string"
                },
                "openID": {
                    "description": "微信 OpenID",
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "points": {
                    "description": "积分",
                    "type": "integer"
                },
                "shoulderWidth": {
                    "description": "肩宽(cm)",
                    "type": "integer"
                },
                "stylePreference": {
                    "description": "偏好数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.StylePreference"
                        }
                    ]
                },
                "totalSpent": {
                    "description": "累计消费金额",
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                },
                "waistSize": {
                    "description": "腰围(cm)",
                    "type": "integer"
                }
            }
        },
        "models.MemberLevel": {
            "type": "string",
            "enum": [
                "regular",
                "silver",
                "gold",
                "platinum",
                "diamond"
            ],
            "x-enum-comments": {
                "Diamond": "钻石会员",
                "Gold": "黄金会员",
                "Platinum": "铂金会员",
                "Regular": "普通会员",
                "Silver": "白银会员"
            },
            "x-enum-varnames": [
                "Regular",
                "Silver",
                "Gold",
                "Platinum",
                "Diamond"
            ]
        },
        "models.PaginatedResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "数据项列表"
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "description": "每页记录数",
                    "type": "integer",
                    "example": 10
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "Brand": {
                    "description": "品牌",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DictionaryItem"
                        }
                    ]
                },
                "BrandID": {
                    "description": "品牌ID",
                    "type": "integer"
                },
                "Category": {
                    "description": "关联",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DictionaryItem"
                        }
                    ]
                },
                "CategoryID": {
                    "description": "商品类别ID",
                    "type": "integer"
                },
                "CostPrice": {
                    "description": "成本价",
                    "type": "number"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Description": {
                    "description": "商品描述",
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "Image": {
                    "description": "主图",
                    "type": "string"
                },
                "Images": {
                    "description": "多张图片，不存储在数据库中，使用ProductImage关联",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Name": {
                    "type": "string"
                },
                "RetailPrice": {
                    "description": "零售价",
                    "type": "number"
                },
                "SKU": {
                    "type": "string"
                },
                "Status": {
                    "description": "状态：上架/下架",
                    "type": "boolean"
                },
                "UpdatedAt": {
                    "type": "string"
                },
                "Variants": {
                    "description": "商品变体",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProductVariant"
                    }
                }
            }
        },
        "models.ProductVariant": {
            "type": "object",
            "properties": {
                "Barcode": {
                    "description": "条形码",
                    "type": "string"
                },
                "Color": {
                    "description": "颜色",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DictionaryItem"
                        }
                    ]
                },
                "ColorID": {
                    "description": "颜色ID",
                    "type": "integer"
                },
                "CostPrice": {
                    "description": "成本价（可能与主商品不同）",
                    "type": "number"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Fabric": {
                    "description": "面料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DictionaryItem"
                        }
                    ]
                },
                "FabricID": {
                    "description": "面料ID",
                    "type": "integer"
                },
                "ID": {
                    "type": "integer"
                },
                "ProductID": {
                    "description": "关联的商品ID",
                    "type": "integer"
                },
                "QRCode": {
                    "description": "二维码数据",
                    "type": "string"
                },
                "RetailPrice": {
                    "description": "零售价（可能与主商品不同）",
                    "type": "number"
                },
                "SKU": {
                    "description": "变体SKU",
                    "type": "string"
                },
                "Season": {
                    "description": "季节",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DictionaryItem"
                        }
                    ]
                },
                "SeasonID": {
                    "description": "季节ID",
                    "type": "integer"
                },
                "Size": {
                    "description": "尺码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DictionaryItem"
                        }
                    ]
                },
                "SizeID": {
                    "description": "尺码ID",
                    "type": "integer"
                },
                "Status": {
                    "description": "状态：启用/禁用",
                    "type": "boolean"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Store": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "manager": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "type": {
                    "description": "男装店/女装店",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.StylePreference": {
            "type": "string",
            "enum": [
                "casual",
                "formal",
                "sportswear",
                "vintage",
                "minimalist",
                "romantic",
                "bohemian",
                "street"
            ],
            "x-enum-comments": {
                "Bohemian": "波西米亚",
                "Casual": "休闲",
                "Formal": "正式",
                "Minimalist": "极简",
                "Romantic": "浪漫",
                "Sportswear": "运动",
                "Street": "街头",
                "Vintage": "复古"
            },
            "x-enum-varnames": [
                "Casual",
                "Formal",
                "Sportswear",
                "Vintage",
                "Minimalist",
                "Romantic",
                "Bohemian",
                "Street"
            ]
        },
        "models.Supplier": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                },
                "city": {
                    "description": "城市",
                    "type": "string"
                },
                "code": {
                    "description": "供应商编码",
                    "type": "string"
                },
                "contactPerson": {
                    "description": "联系人",
                    "type": "string"
                },
                "contactPhone": {
                    "description": "联系电话",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deliveryTerms": {
                    "description": "交货条件",
                    "type": "string"
                },
                "email": {
                    "description": "电子邮箱",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "供应商名称",
                    "type": "string"
                },
                "note": {
                    "description": "备注",
                    "type": "string"
                },
                "paymentTerms": {
                    "description": "付款条件",
                    "type": "string"
                },
                "qualification": {
                    "description": "资质证明",
                    "type": "string"
                },
                "rating": {
                    "description": "供应商评级",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SupplierRating"
                        }
                    ]
                },
                "status": {
                    "description": "状态：true-启用，false-禁用",
                    "type": "boolean"
                },
                "type": {
                    "description": "供应商类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SupplierType"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.SupplierRating": {
            "type": "string",
            "enum": [
                "S",
                "A",
                "B",
                "C",
                "D"
            ],
            "x-enum-comments": {
                "SupplierA": "良好",
                "SupplierB": "一般",
                "SupplierC": "较差",
                "SupplierD": "不合格",
                "SupplierS": "优秀"
            },
            "x-enum-varnames": [
                "SupplierS",
                "SupplierA",
                "SupplierB",
                "SupplierC",
                "SupplierD"
            ]
        },
        "models.SupplierType": {
            "type": "string",
            "enum": [
                "manufacturer",
                "wholesaler",
                "agent",
                "other"
            ],
            "x-enum-comments": {
                "SupplierAgent": "代理商",
                "SupplierManufacturer": "生产厂商",
                "SupplierOther": "其他",
                "SupplierWholesaler": "批发商"
            },
            "x-enum-varnames": [
                "SupplierManufacturer",
                "SupplierWholesaler",
                "SupplierAgent",
                "SupplierOther"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
